### ISSUE TITLE
能否增加form表单中的一些元素?

### ISSUE THREAD

**Issue by jaxwang** [armomu/vue-material-admin#1]
你好,  模板中可否增加一些form表单中的元素?  比如button,文本框 , 单选多选, 滑动开关, 多级联选择 等等, 还有一些提示框toast等等基本元素组件

**Comment by Groundhog-Chen** [comment]
嗯！有空就多加一点进来。

**Comment by timiho** [comment]
可否增加JWT 登录验证(比如:express简单后端)
