### ISSUE TITLE
文件中的敏感信息和不适当的侧边栏展开状态

### ISSUE THREAD

**Issue by RX-105** [armomu/vue-material-admin#33]
1. 关于文件中的敏感信息
`src/layout/layout.vue`，174行，看起来是请求时用的apikey，不知道是作者不小心提交上去了，还是目前已经弃用了。不管是原因如何，我建议这种信息最好不要直接包含在代码中，使用环境变量替代也许更合适。

2. 关于不适当的侧边栏展开状态
`src/layout/layout.vue`，第138行，`navState`中`rail`和`isMini`的取值为`!mainStore.isMobile`，在PC上这个取值为`false`，使得主页侧边栏默认为收起状态，然而在移动端上却默认展开。我认为这并不是侧边栏的合适展示模式，如果作者认为如此的话，可以把`!mainStore.isMobile`修改成`mainStore.isMobile`。

我对开源社区的经验并不多，如果上面说法存在问题，希望作者指正，谢谢。

**Comment by armomu** [comment]
小问题，你们要是要用就pull下来改下就好了，这个不是规范的开源项目，第一次做开源也是一个人维护 哈哈哈哈
