### ISSUE TITLE
Smart Hous 左上角LIVE ROOM控制器相反

### ISSUE THREAD

**Issue by Transparenthw** [armomu/vue-material-admin#34]
用鼠标拖动的时候，从左往右滑当前是视角往右边滚动，如果想往右滑的时候  视图是往左边滚动应该怎么配置？

**Comment by armomu** [comment]
把那个控制器的rotateSpeed设个反向就行
controls.rotateSpeed = -1; // 反转旋转速度

**Comment by Transparenthw** [comment]
> 把那个控制器的rotateSpeed设个反向就行 controls.rotateSpeed = -1; // 反转旋转速度

感谢
