### ISSUE TITLE
请问后端计划实现哪些功能？

### ISSUE THREAD

**Issue by haoxu0809** [armomu/vue-material-admin#37]
是否有计划好的功能内容或清单？
我是 Go 后端开发，目前在学习 Nodejs，平时时间较多。如果不介意的话，我可以来实现后端部分的项目。

**Comment by armomu** [comment]
首先是基础权限这块，再是一个增删改查列的表页，后续可以再计划

**Comment by armomu** [comment]
首先是基础权限这块，再是一个增删改查列的表页，后续可以再计划

**Comment by armomu** [comment]
首先是基础权限这块，再是一个增删改查列的表页，后续可以再计划

**Comment by armomu** [comment]
打算使用Nestjs
