### ISSUE TITLE
空调样式有锯齿

### ISSUE THREAD

**Issue by DDZD20** [armomu/vue-material-admin#38]
调节Air Conditioner的样式有明显的锯齿，感觉和周围的样式配合很突兀。
<img width="415" alt="image" src="https://github.com/user-attachments/assets/12e3572d-69a2-46a5-8bd8-42c58808a9a3">
<img width="801" alt="image" src="https://github.com/user-attachments/assets/fa3a3dde-fef5-4b07-805c-b236be2e7495">

**Comment by armomu** [comment]
再看看是否好一点

**Comment by DDZD20** [comment]
> 再看看是否好一点

好多了
